const $=id=>document.getElementById(id);let lastSnapshot=null;
const slotNames={0:'QB',2:'RB',4:'WR',6:'TE',16:'D/ST',17:'K',20:'BENCH',21:'IR',23:'FLEX'};
const posNames={1:'QB',2:'RB',3:'WR',4:'TE',5:'K',16:'D/ST'};
function setStatus(msg,type=''){const s=$('status');s.textContent=msg;s.className='status '+type}
function inferFromUrl(url=''){try{const u=new URL(url);return{leagueId:u.searchParams.get('leagueId')||'',teamId:u.searchParams.get('teamId')||'',week:u.searchParams.get('scoringPeriodId')||u.searchParams.get('matchupPeriodId')||''}}catch{return{leagueId:'',teamId:'',week:''}}}
function num(v){const n=Number(v);return Number.isFinite(n)?n:null}
function playerRow(entry,week){const p=entry?.playerPoolEntry?.player||{},slot=Number(entry?.lineupSlotId??20);let projection=0,points=0;for(const s of (p.stats||[])){if(Number(s.scoringPeriodId)!==Number(week))continue;if(Number(s.statSourceId)===1)projection=Number(s.appliedTotal||0);if(Number(s.statSourceId)===0)points=Number(s.appliedTotal||0)}return{slot:slotNames[slot]||String(slot),name:p.fullName||'Unknown',pos:posNames[Number(p.defaultPositionId)]||String(p.defaultPositionId??''),team:String(p.proTeamId??''),status:p.injuryStatus||'Active',projection:+projection.toFixed(2),points:+points.toFixed(2),starter:![20,21].includes(slot)}}
function normalize(raw,cfg){const teamId=Number(cfg.teamId),week=Number(cfg.week),teams=Object.fromEntries((raw.teams||[]).map(t=>[Number(t.id),t])),me=teams[teamId];if(!me)throw new Error(`Team ID ${cfg.teamId} was not found in this league.`);let match=null;for(const g of (raw.schedule||[])){if(Number(g.matchupPeriodId)!==week)continue;const h=Number(g.home?.teamId),a=Number(g.away?.teamId);if(h===teamId||a===teamId){match=g;break}}let mySide='home',oppSide='away',oppId=null;if(match){if(Number(match.home?.teamId)===teamId){oppId=Number(match.away?.teamId)}else{mySide='away';oppSide='home';oppId=Number(match.home?.teamId)}}const opp=teams[oppId]||{},players=(me.roster?.entries||[]).map(e=>playerRow(e,week)),lineup=players.filter(p=>p.starter),bench=players.filter(p=>!p.starter),record=me.record?.overall||{},myMatch=match?.[mySide]||{},oppMatch=match?.[oppSide]||{},watch=[];for(const p of lineup){const st=String(p.status||'').toLowerCase();if(/out|injured reserve|doubtful/.test(st))watch.push({priority:'high',title:`${p.name} needs attention`,detail:`Starting ${p.slot} is listed ${p.status}.`});else if(/questionable/.test(st))watch.push({priority:'medium',title:`Monitor ${p.name}`,detail:`Starting ${p.slot} is questionable.`})}const settings=raw.settings||{},budget=Number(settings.acquisitionSettings?.acquisitionBudget),spent=Number(me.transactionCounter?.acquisitionBudgetSpent),faabRemaining=Number.isFinite(budget)&&Number.isFinite(spent)?budget-spent:null;return{meta:{source:'ESPN browser bridge',status:'connected',updatedAt:new Date().toISOString(),season:Number(cfg.season),week,leagueId:String(cfg.leagueId),teamId:String(cfg.teamId)},league:{name:settings.name||raw.name||'ESPN Fantasy',scoring:'ESPN league scoring',waivers:Number.isFinite(budget)?`FAAB $${budget}`:'ESPN waiver rules',playoffs:'ESPN playoff settings'},team:{name:me.name||me.abbrev||'Your Team',record:`${record.wins||0}-${record.losses||0}`,standing:me.playoffSeed??null,faabRemaining,score:Number(myMatch.totalPoints||0),projection:Number(myMatch.totalProjectedPointsLive||0)},opponent:{name:opp.name||opp.abbrev||'Opponent',score:Number(oppMatch.totalPoints||0),projection:Number(oppMatch.totalProjectedPointsLive||0)},lineup,bench,watch}}
async function fetchEspnInPage(cfg){const views=['mSettings','mTeam','mRoster','mMatchup','mMatchupScore'];const base=`https://lm-api-reads.fantasy.espn.com/apis/v3/games/ffl/seasons/${cfg.season}/segments/0/leagues/${cfg.leagueId}`;const qs=new URLSearchParams();for(const v of views)qs.append('view',v);qs.set('scoringPeriodId',cfg.week);const r=await fetch(base+'?'+qs.toString(),{credentials:'include',cache:'no-store'});if(!r.ok)throw new Error(`ESPN returned ${r.status}`);return await r.json()}
async function tryLocalSync(snapshot){const r=await fetch('http://127.0.0.1:43127/espn-sync',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(snapshot)});if(!r.ok)throw new Error(`Local IQ sync returned ${r.status}`);return await r.json()}
function downloadSnapshot(snapshot){const blob=new Blob([JSON.stringify(snapshot,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob);chrome.downloads.download({url,filename:`espn-iq-week-${snapshot.meta.week}.json`,saveAs:true},()=>setTimeout(()=>URL.revokeObjectURL(url),5000))}
async function hydrate(){const [tab]=await chrome.tabs.query({active:true,currentWindow:true});const inferred=inferFromUrl(tab?.url);const saved=await chrome.storage.local.get(['leagueId','teamId','season','week','lastSnapshot']);$('leagueId').value=inferred.leagueId||saved.leagueId||'';$('teamId').value=inferred.teamId||saved.teamId||'';$('season').value=saved.season||'2026';$('week').value=inferred.week||saved.week||'1';lastSnapshot=saved.lastSnapshot||null;$('download').disabled=!lastSnapshot}
$('capture').onclick=async()=>{try{const [tab]=await chrome.tabs.query({active:true,currentWindow:true});if(!tab?.id||!String(tab.url||'').includes('fantasy.espn.com'))throw new Error('Open your ESPN Fantasy league in the active tab first.');const cfg={leagueId:$('leagueId').value.trim(),teamId:$('teamId').value.trim(),season:$('season').value.trim(),week:$('week').value.trim()};if(!cfg.leagueId||!cfg.teamId||!cfg.season||!cfg.week)throw new Error('League ID, Team ID, season, and week are required.');setStatus('Reading ESPN through your existing browser session…');const [{result:raw}]=await chrome.scripting.executeScript({target:{tabId:tab.id},world:'MAIN',func:fetchEspnInPage,args:[cfg]});const snapshot=normalize(raw,cfg);lastSnapshot=snapshot;await chrome.storage.local.set({...cfg,lastSnapshot:snapshot});$('download').disabled=false;try{await tryLocalSync(snapshot);setStatus(`Synced ${snapshot.team.name} to Sunday Funday IQ. No ESPN cookies left the browser.`,'ok')}catch{setStatus(`Captured ${snapshot.team.name}. Local IQ sync is not running yet; snapshot is ready to download.`,'warn')}}catch(e){setStatus(e.message||String(e),'bad')}};
$('download').onclick=()=>lastSnapshot&&downloadSnapshot(lastSnapshot);
hydrate();
